### ISSUE TITLE
Not work for HCN lambda file

### ISSUE THREAD

**Issue by edombek** [mjuvela/LOC#1]
Please check `LOC_aux.MoleculeO.Read` for https://home.strw.leidenuniv.nl/~moldata/datafiles/hcn.dat

Thanks

**Comment by mjuvela** [comment]
This was corrected a while back, and code (LOC1D.py, LOC_OT.py)  should now allow the input file to have different Tkin grids for the collisional coefficients of different collisional partners. If some partner has data for fewer Tkin values, these are padded using the collisional coefficient of the originally highest Tkin value (~copied, not extrapolated). If for some collisional partner the input file does not list the  collisional coefficients for all transitions, the value of the missing transitions remain zero. To fill in missing values (i.e. using proper extrapolation for higher/lower Tkin values or adding values for the missing transitions), one should do that outside LOC and provide LOC with a suitably edited file.

**Comment by edombek** [comment]
Ok, thanks!!!
